import React from 'react';
import './Home.css'

const Terms = () => {
    return (
        <div className='terms'>
            <h1>Terms of Service</h1><br/>
            <h2>PART 1 GENERAL CONDITIONS</h2><br/>
            <h3>§ 1 Scope of application</h3><br/>
            <p>Our Terms of Use apply to the use of this website and to all - including future - contracts with our customers regarding our services. Any terms and conditions of the customer that conflict with or deviate from our terms and conditions of use shall not be recognized. Our Terms of Use shall also apply if we perform our services without reservation in the knowledge of terms and conditions of the customer that conflict with or deviate from our Terms of Use. The use of our website and services is at the customer's own risk.</p><br/>
            <h3>§ 2 Performance obligations of Our website</h3><br/>
            <p>1. Our performance obligations result from the performance description of the respective product. Other commitments, promises of performance or ancillary agreements are only effective if they are confirmed by us in writing. We reserve the right to make changes and adjustments to the service offered, even in the case of contracts already in progress, due to various circumstances, for example technical circumstances (e.g., updates) or legal requirements. In the event of changes, we shall strive to offer you an equivalent service. If, in our reasonable discretion, this is not possible or does not appear to be possible, we may also replace the previous service with an inferior service that comes as close as possible to the previous one.<br/>
            (2) We are entitled to expand our services, adapt them to technical progress and/or make improvements. This applies in particular if the adjustment appears necessary to prevent misuse or if we are obliged to adjust our services due to legal regulations.<br/>
            (3) If we provide additional services without additional remuneration, the customer shall have no claim to performance of such services. We shall be entitled to discontinue or change such services, which were previously provided free of charge, or to offer them only against payment within a reasonable period of time. In such a case, we will inform the customer in good time.<br/>
            (4) We are only obligated to provide technical support to the customer within the scope of what has been contractually agreed. Any further support services shall not be granted.</p><br/>
            <h3>§ 3 Obligations of the customer</h3><br/>
            <p>(1) The customer warrants that the information provided by him/her is correct and complete. The customer undertakes to inform Our website without delay of any changes to the contact details provided and of any other data required for the performance of the contract. The customer warrants that he/she is at least 18 years old, has full legal capacity according to the applicable laws and does not have his/her permanent residence in the United States of America (USA).<br/>
            (2) You may not be able to make full use of all of our services depending on your country of residence and the laws applicable in your country of residence. You are solely responsible for deciding whether this is applicable to you and indemnify us against any liability that may arise as a result. We reserve the right to cancel your contracts, terminate them early, block your access if you breach any applicable law. Contracts you enter into without complying with the law applicable to you may be invalid. You are not entitled to any refunds in the event of invalidity.<br/>
            (3) The customer undertakes to regularly change the passwords received from us for the purpose of accessing our services and to keep them strictly secret. The customer shall inform us immediately as soon as it becomes aware that unauthorised third parties are aware of the password.<br/>
            (4) The customer further undertakes not to use the resources made available by us for actions that violate legal prohibitions, morality, and the rights of third parties.</p><br/>
            <h3>§ 4 Conclusion of contract, term of contract, termination</h3><br/>
            <p>1) The contract is concluded by our acceptance of the customer's contract offer. The acceptance is either expressly declared or is to be seen in the beginning of the execution of our services.<br/>
            (2) Unless otherwise agreed, the contracts run for as long as is shown to you when you select our service. After expiry of the agreed term, the contracts end automatically without the need for termination. Ordinary termination during the fixed term is excluded.<br/>
            (3) The right of both parties to extraordinary termination for good cause remains unaffected.</p><br/>
            <h3>§ 5 Prices and payment</h3><br/>
            <p>(1) The fees to be paid for our services are due and payable in advance for the respective contract term unless a different billing period has been agreed with the customer. Acceptance of the offer to the customer shall only take place upon payment in full.<br/>
            (2) We may charge maintenance fees. These may include various costs such as electricity, administration, spare parts, wear, and tear and more. If contracts with maintenance fees exist, the amount of the maintenance fees may change during the term and be adjusted by us. A certain amount is budgeted for this cost area at the time of conclusion, including increases in prices due to inflation. We reserve the right to adjust the maintenance fees accordingly in the event of an increase of at least 10 percent of the underlying costs. In order to ensure the stable operation of the mining machine.<br/>
            (3) The payment methods and payment options accepted by us are displayed in the dashboard for the respective contracts.</p><br/>
            <h3>§ 6 Warranty</h3><br/>
            <p>(1) The customer shall notify us of any defects without delay and shall support us to the best of his ability in the event of a possible rectification of defects, in particular by taking all reasonable measures for data security.<br/>
            (2) We expressly point out that, according to the current state of the art, it is not possible to create hardware and software in such a way that it works error-free in all application combinations or can be protected against any manipulation by third parties. We therefore do not guarantee that the hardware and software used or provided by us is free of crashes, errors, or malware. We warrant to the customer only that the hardware and software used by us will function at the time under normal operating conditions and normal maintenance substantially in accordance with the manufacturer's performance specifications for the provision of our services. We further do not warrant that the hardware and software we use will be available at all times. We reserve the right to interrupt our service provision due to maintenance work, updates, power failures or force majeure.</p><br/>
            <h3>§ 7 Liability, exclusion of liability for representatives of the Company</h3><br/>
            <p>(1) We shall be liable, irrespective of the legal grounds and to the extent permitted by law, only in accordance with the following provisions.<br/>
            (2) We offer our services (in particular website, information, dashboard) to the best of our knowledge and with the competence available to us. We do not assume any liability that our services always correspond to the latest state of technology and knowledge. This applies to all functions, but especially to purely informative functions as well as to security-relevant functions.<br/>
            (3) The information provided by us is partly of a general nature. You should not use it solely to make personal decisions. Consult suitable experts for your decisions and use advice tailored to your personal situation. We accept no liability whatsoever, to the extent permitted by law, for any erroneous decisions made by you on the basis of information provided by us.<br/>
            (4) We do not assume any warranty or liability, even implied, for our website or services offered. The provision takes place "AS IS" as well as "AS AVAILABLE".<br/>
            (5) We assume no liability for any malfunctions, failures, interruptions, inaccuracies, or damage caused by third parties.<br/>
            (6) We do not give any assurances that our services will be usable at any time or in the long term, in particular not insofar as our services are restricted or made impossible by legal requirements. In this case, we assume no liability for any direct or consequential damages incurred by you.<br/>
            (8) To the extent permitted by law, we do not accept any liability for damage caused by legal incorrectness, loss of data or misuse of services, faulty performance by suppliers or affiliated companies, of products provided, including licensed software products.<br/>
            (9) Claims for damages by you against us are excluded to the extent permitted by law.<br/>
            (10) Insofar as our liability is excluded or limited and to the extent permitted by law, this shall also apply to the liability of our employees, other staff, representatives, and vicarious agents.</p><br/>
            <h3>§ 8 Data protection</h3><br/>
            <p>We collect, process, and use personal data of the customer within the framework of the statutory data protection provisions. By transferring user content or data, you grant us and our affiliated companies and service providers an irrevocable, non-exclusive right of use. This includes in particular, but is not limited to, the right of use for administrative processes in the context of your account and contract management. Supplementary information on this can be found in the data protection declaration.</p><br/>
            <h3>§ 9 Copyrights, License Agreements</h3><br/>
            <p>(1) We grant the customer a time-limited, non-exclusive (simple), revocable right of use to our own and third-party software provided. The transfer, except with our consent by way of contract assumption, as well as the granting of sublicenses to third parties are not permitted. Further use after termination of the contract is not permitted.<br/>
            (2) For open-source programs, the respective valid license terms of the software provider also apply. You can obtain these from the respective provider. We are not obliged to provide or obtain these license terms for you. If the terms and conditions of the software provider conflict with these terms and conditions, the terms and conditions of the software provider take precedence.</p><br/>
            <h3>§ 10 Exemption</h3><br/>
            <p>The customer undertakes to indemnify us internally against all possible claims by third parties which are based on illegal or infringing actions by the customer or errors in the content of the information provided by the customer, its use, or its infringement of the rights of third parties.</p><br/>
            <h3>§ 11 Communication</h3><br/>
            <p>All information and declarations from Our website will be addressed to the customer exclusively by electronic means, in particular via the dashboard or by e-mail to the e-mail address provided by the customer. We decide on the way of delivery of the information or statements at our reasonable discretion. We are not obliged to check whether you have received this information or explanation.</p><br/>
            <h3>§ 12 Changes to the GTC</h3><br/>
            <p>We may unilaterally change these Terms of Use and have posted the most current form on our website at all times. Changes will be published on this website. We are not obliged to inform you separately about changes. It is your responsibility to check this website regularly for changes. If you continue to use our services after a change has been made, you accept the changes.</p><br/>
            <h3>§ 13 Law</h3><br/>
            <p>These Terms of Use shall be governed by and construed in accordance with the laws of the UK.</p><br/>
            <h3>§ 14 Severability clause</h3><br/>
            <p>If any provision of these Terms of Use is found to be invalid, the validity of the remaining provisions shall not be affected. They will be replaced by an enforceable and valid provision that reflects our intention as closely as possible</p><br/><br/>
            <h2>PART 2 RISK NOTICE</h2><br/>
            <p>Our services are related to cryptocurrencies. We therefore draw the customer's attention to the fact that various risks can arise that are typically associated with an investment or an arrangement in the area of cryptocurrencies or cryptomining. In particular, there is always the risk of a total loss. The crypto sector is still a largely unregulated market. The customer therefore expressly accepts these risks.</p><br/><br/>
            <h2>PART 3 DEFINITIONS</h2><br/>
            <p><strong>Our website:</strong> is the website through which the company presents and offers its information and services and through which the customers or interested parties or users can obtain information, register, conclude contracts and, in the case of existing registration or contracts, find a management (dashboard) for it.<br/>
            DashboardApp: is the graphical management platform for registered users of the Our website website, accessible through a login process via the Our website website.
            Registration: is the process by which you register as a user of our website in order to be able to use further services or to be able to purchase further services (also for sale).
            Login process: is the process users perform to access their dashboard by entering their user-related data (known only to the user himself).<br/>
            <strong>Rig:</strong> is a device used to mine for Ethereum or other altcoins. It consists of various components such as multiple graphics cards, motherboard, power supplies and other components. It is powered and connected to the network of the coin to be mined and calculates transactions for the network. In return, the network rewards the computing power with its coins.<br/>
            <strong>Wallet:</strong> is an electronic wallet. This wallet or purse electronically stores funds.<br/>
            <strong>Wallet address</strong>: is the electronic address of your wallet, it usually consists of a long combination of characters.<br/>
            <strong>Transaction fees:</strong> are fees that are charged by the network or that may be incurred voluntarily in order to execute or confirm certain transactions (i.e., transfers or logging). Depending on the network, transaction fees are also used to pay the miners.<br/>
            <strong>Network fees:</strong> are fees charged by the network that may apply to transactions.</p><br/>
        </div>
    );
};

export default Terms;